sudo: false
dist: trusty
language: java

matrix:
  include:
    - env:
        - WITH_PAPI=true
      addons:
        apt:
          packages:
            - libpapi-dev
    - env:
        - WITHOUT_PAPI=true

os:
  - linux

addons:
  apt:
    packages:
      - ant-optional

script:
  - "echo 'agent.cc.warnings = aserror' >local-settings.ini"
  - ant print-config
  - ant print-properties
  - ant list-events
  - gcc --version
  - ant test-junit
  - ant checkstyle
