language: java
env:
  matrix:
   - WITH_PAPI=true
   - WITH_PAPI=false
before_install:
 - sudo apt-get install ant-optional
 - "$WITH_PAPI && sudo apt-get install libpapi-dev"
script:
 - ant print-config
 - ant print-properties
 - ant list-events
 - gcc --version
 - ant test-junit
os:
 - linux
