sudo: false
dist: trusty
language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      env:
        - CHECKSTYLE=yes
    - os: linux
      jdk: oraclejdk8
      env:
        - WITH_PAPI=yes
      addons:
        apt:
          packages:
            - libpapi-dev
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk9
    - os: linux
      jdk: oraclejdk10
    - os: linux
      jdk: openjdk7
    - os: linux
      jdk: openjdk8
    - os: osx

addons:
  apt:
    packages:
      - ant-optional

before_install:
  - 'if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ant; fi'
  - 'if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi'

script:
  - 'if [ "$CHECKSTYLE" = "yes" ]; then ant checkstyle && travis_terminate 0; fi'
  - "echo 'agent.cc.warnings = aserror' >local-settings.ini"
  - "echo 'agent.cc.extra.flags = -DUBENCH_DEBUG' >>local-settings.ini"
  - ant print-config
  - ant print-properties
  - ant lib
  - ant list-events
  - gcc --version
  - ant test-junit
