sudo: false
dist: trusty
language: java

matrix:
  include:
    - jdk: oraclejdk8
      addons:
        apt:
          packages:
            - libpapi-dev
    - jdk: oraclejdk8
    - jdk: oraclejdk9
    - jdk: openjdk8
    - jdk: openjdk7
    - jdk: openjdk6
      addons:
        apt:
          packages:
            - openjdk-6-jdk

os:
  - linux

addons:
  apt:
    packages:
      - ant-optional

script:
  - "echo 'agent.cc.warnings = aserror' >local-settings.ini"
  - ant print-config
  - ant print-properties
  - ant list-events
  - gcc --version
  - ant test-junit
  - ant checkstyle
