name: Main
on:
  push:
    branches: [master]
  pull_request:
jobs:
  linux-jdk8:
    runs-on: ubuntu-latest
    container: "registry.gitlab.com/mffd3s/java/ubench-agent:v1"
    continue-on-error: true
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Run gate
        shell: bash
        run: env JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk ant -Dagent.feature.want.papi=false gate

  macos:
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Run gate
        shell: bash
        run: ant -Dtest.classes.excluded=**/ThreadTimeTest.class gate

  windows:
    runs-on: windows-latest
    continue-on-error: true
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Run gate
        run: ant '"-Dagent.cc=msvc"' gate
